<template>
    <div>
        <h1 class="text-primary text-5xl leading-12 font-bold tracking-tight">
            Laravel Web Application
        </h1>
        <p class="text-xl mt-8">
            The application is built using a client-server architecture. The frontend is a server-side-rendered
            <a href="https://nuxt.com" target="_blank" class="underline hover:text-primary">Nuxt.js</a>
            service that talks to the REST API of the backend, which is built in
            <a href="https://laravel.com" target="_blank" class="underline hover:text-primary">Laravel</a>.
        </p>
        <h2 class="mt-8 text-2xl font-bold text-primary tracking-tight leading-tight">
            Pages
        </h2>
        <ul class="mt-6 space-y-4">
            <li v-for="page in pages" class="flex space-x-4">
                <a :href="page.url" class="underline hover:text-primary">
                    {{ page.url }}
                </a>
                <p>
                    {{ page.description }}
                </p>
            </li>
        </ul>
    </div>
</template>

<script lang="ts">
import Vue from 'vue'

interface Page {
    url: string
    description: string
}

export default Vue.extend({
    data() {
        return {
            pages: [
                {
                    url: '/lorem-ipsum',
                    description: 'This page shows static content and does not interact with the backend.'
                },
                {
                    url: '/users?n=100',
                    description: 'This page shows n users randomly generated by the backend.'
                },
                {
                    url: '/fibonacci?n=25',
                    description: 'This page shows the nth Fibonacci number calculated by the backend.'
                },
            ] as Page[],
        }
    }
})
</script>
