<template>
    <div>
        <h1 class="text-primary text-5xl leading-12 font-bold tracking-tight">
            Users
        </h1>
        <p class="text-xl mt-8">
            This page shows n users randomly generated by the backend.
        </p>
        <div class="mt-8">
            <p v-if="$fetchState.pending">
                Fetching data from backend...
            </p>
            <p v-else-if="$fetchState.error">
                An error occurred :(
            </p>
            <div v-else class="grid grid-cols-5 gap-4">
                <template v-for="(user, index) of users">
                    <div>
                        {{ index + 1 }}.
                    </div>
                    <div class="col-span-2">
                        {{ user.name }}
                    </div>
                    <div class="col-span-2">
                        {{ user.email }}
                    </div>
                </template>
            </div>
        </div>
        <button @click="$fetch" class="mt-8 bg-accent text-primary rounded px-3 py-1">
            Refresh
        </button>
    </div>
</template>

<script lang="ts">
import Vue from 'vue'

interface User {
    name: string
    email: string
}

export default Vue.extend({
    data: () => ({
        n: 0 as number,
        users: [] as User[]
    }),
    watch: {
        '$route.query': '$fetch'
    },
    async fetch() {
        const response = await this.$axios.$get('/api/users', {
            params: {
                n: this.parseN()
            },
        })

        this.n = response.n
        this.users = response.users
    },
    methods: {
        parseN(): number {
            let n = this.$route.query.n || '200'

            if (Array.isArray(n)) {
                n = n[0] || '200'
            }

            return parseInt(n)
        },
    }
})
</script>
